### ISSUE TITLE
Several questions and ideas

### ISSUE THREAD

**Issue by PaulMaly** [sveltejs/svelte.technology#32] opened 2017-01-30 22:58 UTC
Hi, Rich! 

First of all, let me thank you for this great idea. And also I know that you're founder and one of main maintainers of RactiveJS - best JS framework I ever used. I believe that Svelte has really great prospects. Thank you for that.

For me Svelte could be great because of several reasons:
- I already use RactiveJS the last 3 years and obviously Svelte has very similar API
- I'm already using Webpack to build my code and it's great if this process will transform my code to vanilla JS

But right now Svelte is a little bit dampish and it's justified. Main questions for me to make a decision to switch from Ractive to Svelte would be:
- integration with complex data structures (not POJO objects, like classes etc.). In Ractive we've Adaptors and it's great tool to do something like this:

`ractive.set('post', fetch('/posts')); // using Promise adaptor`

- integration with DOM specific libraries (like Jquery etc.). In Ractive we've Decorators and I never get a problem with it and even more - it helps me encapsulate my browser specific code in my isomorphic (universal) apps.

Whether you plan to include similar features in Svelte ? 

And my main idea - Ractive API is awesome, just implement it. Thanks!

**Comment by Rich-Harris** [comment] 2017-04-12 15:55
Closing this as dupe of https://github.com/sveltejs/svelte/issues/272

**Closed by Rich-Harris** 2017-04-12 15:55 UTC
